name: calibcam
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy<2
  - opencv>=4.7.0
  - py-opencv>=4.7.0
  - pyyaml
  - scipy
  - imageio
  - joblib
  - cudatoolkit
  - appdirs
  - pip
  - pip:
    - jaxlib
    - jax
    - pytest
    - pytest-cov
    - bbo-ccvtools
    - bbo-calibcamlib
    - bbo-calibcam
    - bbo-svidreader
