name: calibcam
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - opencv=4.6.0
  - py-opencv=4.6.0
  - pyyaml
  - scipy
  - imageio
  - joblib
  - cudatoolkit
  - appdirs
  - pip
  - pip:
    - jaxlib
    - jax
    - bbo-ccvtools
    - bbo-calibcamlib
    - bbo-calibcam
    - git+https://github.com/bbo-lab/videoreader.git@dev
